- name: OpenAPI Specification | Swagger
  url: 'https://swagger.io/specification/'
  pull_url: 0
  pull_domain: 0
- name: Gmail API | Google Developers
  url: 'https://developers.google.com/gmail/api/'
  pull_url: 0
  pull_domain: 0
- name: Create an OpenAPI definition for a function with Azure API ...
  url: >-
    https://docs.microsoft.com/en-us/azure/azure-functions/functions-openapi-definition
  pull_url: 0
  pull_domain: 0
- name: Create a custom connector from an OpenAPI definition ...
  url: >-
    https://docs.microsoft.com/en-us/connectors/custom-connectors/define-openapi-definition
  pull_url: 0
  pull_domain: 0
- name: Email Marketing API | Email API Integration | Open API ...
  url: 'https://www.netatlantic.com/emailmarketing/openapi'
  pull_url: 0
  pull_domain: 0
- name: Announcing the preview of OpenAPI Specification v3 support ...
  url: >-
    https://azure.microsoft.com/en-us/blog/announcing-the-preview-of-openapi-specification-v3-support-in-azure-api-management/
  pull_url: 0
  pull_domain: 0
- name: OAI/OpenAPI-Specification - GitHub
  url: 'https://github.com/OAI/OpenAPI-Specification/tree/master/examples/v3.0'
  pull_url: 0
  pull_domain: 0
- name: 'OpenAPI 1.2 API: How To Use the API | RapidAPI'
  url: 'https://rapidapi.com/transloc/api/openapi-1-2/details'
  pull_url: 0
  pull_domain: 0
- name: OpenAPI-GUI v3.0.0 - GitHub Pages
  url: 'https://mermade.github.io/openapi-gui/'
  pull_url: 0
  pull_domain: 0
- name: About - OpenAPI Initiative
  url: 'https://www.openapis.org/about'
  pull_url: 0
  pull_domain: 0
- name: Tool up your API integration testing with OpenAPI | TechBeacon
  url: >-
    https://techbeacon.com/app-dev-testing/tool-your-api-integration-testing-openapi
  pull_url: 0
  pull_domain: 0
- name: Home - OpenAPI Initiative
  url: 'https://www.openapis.org/'
  pull_url: 0
  pull_domain: 0
- name: 'JSON API, OpenAPI and JSON Schema Working in Harmony ...'
  url: >-
    https://apisyouwonthate.com/blog/json-api-openapi-and-json-schema-working-in-harmony/
  pull_url: 0
  pull_domain: 0
- name: 'GitHub - microsoft/OpenAPI.NET: The OpenAPI.NET SDK ...'
  url: 'https://github.com/Microsoft/OpenAPI.NET'
  pull_url: 0
  pull_domain: 0
- name: The Best APIs are Built with Swagger Tools | Swagger
  url: 'https://swagger.io/'
  pull_url: 0
  pull_domain: 0
- name: API Overview | HubSpot API
  url: 'https://developers.hubspot.com/docs/overview'
  pull_url: 0
  pull_domain: 0
- name: Documenting .NET Web Services using OpenAPI (formally ...
  url: >-
    https://blog.learningtree.com/documenting-net-web-services-using-openapi-formally-swagger-and-swashbuckle/
  pull_url: 0
  pull_domain: 0
- name: AnyAPI
  url: 'https://any-api.com/'
  pull_url: 0
  pull_domain: 0
- name: Open API - Wikipedia
  url: 'https://en.wikipedia.org/wiki/Open_API'
  pull_url: 0
  pull_domain: 0
- name: Transactional Email API Service For Developers | Mailgun
  url: 'https://www.mailgun.com/'
  pull_url: 0
  pull_domain: 0
- name: 'Browse APIs - API tooling development: GraphQL, OpenAPI'
  url: 'https://apis.guru/browse-apis/'
  pull_url: 0
  pull_domain: 0
- name: How can I validate OpenAPI's Schema Object - Stack Overflow
  url: >-
    https://stackoverflow.com/questions/50644414/how-can-i-validate-openapis-schema-object
  pull_url: 0
  pull_domain: 0
- name: Open API vz REST API - difference - Stack Overflow
  url: 'https://stackoverflow.com/questions/48123867/open-api-vz-rest-api-difference'
  pull_url: 0
  pull_domain: 0
- name: OpenAPI 3.0 tutorial overview | Documenting REST APIs
  url: >-
    https://idratherbewriting.com/learnapidoc/pubapis_openapi_tutorial_overview.html
  pull_url: 0
  pull_domain: 0
- name: List of 10+ Email APIs - KongHQ - Kong API Gateway
  url: 'https://konghq.com/blog/list-of-10-email-apis/'
  pull_url: 0
  pull_domain: 0
