- name: Using Firebase to authenticate users | Cloud Endpoints ...
  url: >-
    https://cloud.google.com/endpoints/docs/openapi/authenticating-users-firebase
  pull_url: 0
  pull_domain: 0
- name: Centurylink OpenAPI Services - Level 3 Communications
  url: 'https://developer.level3.com/documentation'
  pull_url: 0
  pull_domain: 0
- name: Free Email API Service for Developers - Quick and Easy to ...
  url: 'https://www.mailjet.com/email-api/'
  pull_url: 0
  pull_domain: 0
- name: Documenting your API with OpenAPI (Swagger) and Redoc
  url: >-
    https://itnext.io/documenting-your-api-with-openapi-swagger-and-redoc-417bd8304b72
  pull_url: 0
  pull_domain: 0
