- name: APIEMR & Practice Management Software Vendors
  url: 'https://www.micromd.com/api/'
  pull_url: 0
  pull_domain: 0
- name: 'apigee | Google Cloud - API Design, From A to Z'
  url: 'https://pages.apigee.com/api-design-register.html'
  pull_url: 0
  pull_domain: 0
- name: SendGrid Managing Their OpenAPI Using GitHub - DZone 
  url: 'https://dzone.com/articles/sendgrid-managing-their-openapi-using-github'
  pull_url: 0
  pull_domain: 0
- name: 'Programming with Java APIs, Part 1: OpenAPI and Swagger ...'
  url: >-
    https://www.javaworld.com/article/3199351/api-driven-development-with-openapi-and-swagger.html
  pull_url: 0
  pull_domain: 0
- name: Documenting an ASP.NET Core API with OpenAPI / Swagger
  url: 'https://www.pluralsight.com/courses/aspdotnet-core-api-openapi-swagger'
  pull_url: 0
  pull_domain: 0
- name: Generate Spring Boot REST API using Swagger/OpenAPI – 47 ...
  url: >-
    https://www.47northlabs.com/knowledge-base/generate-spring-boot-rest-api-using-swagger-openapi/
  pull_url: 0
  pull_domain: 0
- name: Manage your specifications | Apigee Docs
  url: 'https://docs.apigee.com/api-platform/publish/specs/manage-specs'
  pull_url: 0
  pull_domain: 0
- name: API Development with Swagger - Developer.com
  url: 'https://www.developer.com/java/data/api-development-with-swagger.html'
  pull_url: 0
  pull_domain: 0
- name: OpenAPI v3 support in Azure API Management | Azure updates ...
  url: >-
    https://azure.microsoft.com/en-us/updates/openapi-v3-support-in-azure-api-management/
  pull_url: 0
  pull_domain: 0
- name: API Launch Announcement from DevNet Create - Cisco Meraki Blog
  url: >-
    https://meraki.cisco.com/blog/2019/04/api-launch-announcement-from-devnet-create/
  pull_url: 0
  pull_domain: 0
- name: Create swagger api endpoint for Azure functions
  url: >-
    https://ratsubsharewall.blogspot.com/2017/12/create-swagger-api-endpoint-for-azure.html
  pull_url: 0
  pull_domain: 0
- name: Writing OpenAPI (Swagger) Specification Tutorial - Part 7 ...
  url: >-
    https://apihandyman.io/writing-openapi-swagger-specification-tutorial-part-7-documentation/
  pull_url: 0
  pull_domain: 0
- name: Building APIs with OpenAPI – Ratros Y. – Medium
  url: 'https://medium.com/@ratrosy/building-apis-with-openapi-ac3c24e33ee3'
  pull_url: 0
  pull_domain: 0
- name: OpenAPI Spec (Swagger Spec) Generator - Online tool to ...
  url: >-
    https://community.apigee.com/articles/25770/openapi-spec-swagger-spec-generator-online-tool-to.html
  pull_url: 0
  pull_domain: 0
- name: How to use IBM App Connect with APIs imported from OpenAPI ...
  url: >-
    https://developer.ibm.com/integration/docs/app-connect/how-to-guides-for-apps/use-ibm-app-connect-openapi/
  pull_url: 0
  pull_domain: 0
- name: docs.waiverforever.com - WavierForever Open API v1.0.0
  url: 'https://docs.waiverforever.com/'
  pull_url: 0
  pull_domain: 0
- name: OpenFEC API Documentation
  url: 'https://api.open.fec.gov/developers/'
  pull_url: 0
  pull_domain: 0
- name: Open API - ServiceStack
  url: 'https://docs.servicestack.net/openapi'
  pull_url: 0
  pull_domain: 0
- name: Part 6 - Defining Security - API Handyman
  url: >-
    https://apihandyman.io/writing-openapi-swagger-specification-tutorial-part-6-defining-security/
  pull_url: 0
  pull_domain: 0
- name: Swagger Editor
  url: 'https://editor.swagger.io/'
  pull_url: 0
  pull_domain: 0
- name: Swagger Is Now The OpenAPI Specification | Build Azure
  url: 'https://buildazure.com/2017/10/20/swagger-is-now-the-openapi-specification/'
  pull_url: 0
  pull_domain: 0
- name: Open API Manifesto - TM Forum
  url: 'https://www.tmforum.org/open-apis/open-api-manifesto/'
  pull_url: 0
  pull_domain: 0
- name: Introducing Swagger UI on Azure Functions – DevKimchi
  url: 'https://devkimchi.com/2019/02/02/introducing-swagger-ui-on-azure-functions/'
  pull_url: 0
  pull_domain: 0
- name: All API documentation - developer.ebay.com
  url: 'https://developer.ebay.com/docs'
  pull_url: 0
  pull_domain: 0
- name: 'RepreZen API Studio: Breakthrough Productivity for Swagger ...'
  url: 'https://www.reprezen.com/'
  pull_url: 0
  pull_domain: 0
- name: SMTP Web API for email delivery - SMTP.com
  url: 'https://www.smtp.com/developers/smtp-api/'
  pull_url: 0
  pull_domain: 0
- name: 'Build, Collaborate & Integrate APIs | SwaggerHub'
  url: 'https://app.swaggerhub.com/'
  pull_url: 0
  pull_domain: 0
- name: 'Building APIs with OpenAPI: Continued – Ratros Y. – Medium'
  url: >-
    https://medium.com/@ratrosy/building-apis-with-openapi-continued-5d0faaed32eb
  pull_url: 0
  pull_domain: 0
- name: Comparing OpenAPI with gRPC – Red Hat Services Speak
  url: 'https://servicesblog.redhat.com/2019/01/31/comparing-openapi-with-grpc/'
  pull_url: 0
  pull_domain: 0
- name: Microsoft Graph - Home
  url: 'https://developer.microsoft.com/en-us/graph/'
  pull_url: 0
  pull_domain: 0
- name: OpenAPI code generators for Visual Studio | endjin blog
  url: 'https://blogs.endjin.com/2018/04/openapi-code-generators-for-visual-studio/'
  pull_url: 0
  pull_domain: 0
- name: OpenAPI Enumerators Add Dimensions To Each API Call
  url: >-
    https://apifriends.com/api-streaming/openapi-enumerators-add-dimensions-api-call/
  pull_url: 0
  pull_domain: 0
- name: 'REST API Design: Filtering, Sorting, and Pagination ...'
  url: >-
    https://www.moesif.com/blog/technical/api-design/REST-API-Design-Filtering-Sorting-and-Pagination/
  pull_url: 0
  pull_domain: 0
- name: API Marketplace - Free Public & Open Rest APIs | RapidAPI
  url: 'https://rapidapi.com/'
  pull_url: 0
  pull_domain: 0
- name: Our API Specification Workflow – WeWork Technology
  url: 'https://engineering.wework.com/our-api-specification-workflow-9337448d6ee6'
  pull_url: 0
  pull_domain: 0
- name: Modelling OpenAPI - Swagger 2.0 Specification using API ...
  url: >-
    https://www.ibm.com/cloud/blog/modelling-openapi-swagger-2-0-specification-using-api-connect
  pull_url: 0
  pull_domain: 0
- name: Streamdata.io Documentation
  url: 'https://streamdataio.github.io/streamdataio-docker/'
  pull_url: 0
  pull_domain: 0
- name: how to use mailGun API - YouTube
  url: 'https://www.youtube.com/watch?v=MBWYn7M4yFg'
  pull_url: 0
  pull_domain: 0
- name: RESTful APIs and Swagger (OpenAPI) in Azure Functions
  url: 'https://anthonychu.ca/post/restful-apis-swagger-openapi-azure-functions/'
  pull_url: 0
  pull_domain: 0
- name: Describe Your API With OpenAPI | recallact.com
  url: 'https://www.recallact.com/presentation/describe-your-api-openapi'
  pull_url: 0
  pull_domain: 0
- name: D&B Direct+ Documentation
  url: 'https://directplus.documentation.dnb.com/openAPI.html?apiID=IDRExtendedMatch'
  pull_url: 0
  pull_domain: 0
- name: New Open Source Project – VMware OpenAPI Generator ...
  url: 'https://blogs.vmware.com/code/2018/12/07/new-vmware-openapi-generator/'
  pull_url: 0
  pull_domain: 0
- name: It's Time For Every API to Have an OpenAPI Spec ...
  url: >-
    https://www.programmableweb.com/news/its-time-every-api-to-have-openapi-spec/sponsored-content/2018/12/19
  pull_url: 0
  pull_domain: 0
- name: Sports Data OpenAPI | Fantasy Sports API Swagger Files ...
  url: 'https://sportsdata.io/developers/sports-data-open-api-swagger-files'
  pull_url: 0
  pull_domain: 0
- name: 'Mojolicious, OpenAPI - and GraphQL - mojolicious.io'
  url: 'https://mojolicious.io/blog/2018/03/18/graphql-openapi/index.html'
  pull_url: 0
  pull_domain: 0
- name: 'Custom Connector, Microsoft (Graph) OpenAPI (2/3 ...'
  url: >-
    https://powerusers.microsoft.com/t5/General-Discussion/Custom-Connector-Microsoft-Graph-OpenAPI-2-3-Extension-for/td-p/140493
  pull_url: 0
  pull_domain: 0
- name: GitHub API v3 | GitHub Developer Guide
  url: 'https://developer.github.com/v3/'
  pull_url: 0
  pull_domain: 0
- name: OData to OpenAPI Mapping Version 1.0 - OASIS
  url: >-
    http://docs.oasis-open.org/odata/odata-openapi/v1.0/cnprd01/odata-openapi-v1.0-cnprd01.html
  pull_url: 0
  pull_domain: 0
- name: NASA Open APIs - NASA API Listing
  url: 'https://api.nasa.gov/'
  pull_url: 0
  pull_domain: 0
- name: Groups Service API v3 - IAM - UW-IT Wiki
  url: 'https://wiki.cac.washington.edu/display/infra/Groups+Service+API+v3'
  pull_url: 0
  pull_domain: 0