- name: Expressing What An API Does As Well As What Is Possible
  url: >-
    https://blog.apievangelist.com/2017/05/01/expressing-what-an-api-does-as-well-as-what-is-possible-using-openapi/
  pull_url: 0
  pull_domain: 0
- name: Tutorial  RingCentral Developers  Medium
  url: 'https://medium.com/ringcentral-developers/tagged/tutorial'
  pull_url: 0
  pull_domain: 0
- name: Twilio SMS API Provider Se Cloud Elements Help Center
  url: 'https://docs.cloud-elements.com/home/twilio-sms-api-provider-setup'
  pull_url: 0
  pull_domain: 0
- name: Kong Next-Generation API platform for Microservices
  url: 'https://konghq.com/'
  pull_url: 0
  pull_domain: 0
- name: Are there any open source API Gateways?Quora
  url: 'https://www.quora.com/Are-there-any-open-source-API-Gateways'
  pull_url: 0
  pull_domain: 0
- name: openapi.sms.uplus.co.kr
  url: 'https://openapi.sms.uplus.co.kr/sdkFile/java_sdk-0.0.1.jar'
  pull_url: 0
  pull_domain: 0
- name: App CenterD&B Direct API
  url: 'https://developer.dnb.com/marketplace/apps'
  pull_url: 0
  pull_domain: 0
- name: Generating PowerShell Cmdlets from OpenAPI/Swagger with
  url: >-
    https://msviennatechnoblog.wordpress.com/2019/02/22/generating-powershell-cmdlets-from-openapi-swagger-with-autorest/
  pull_url: 0
  pull_domain: 0
- name: Teknospire Inspiring Technologies for Better Livings
  url: 'http://blog.teknospire.com/2017/10/openbanking-inclusive-opendata-openapi/'
  pull_url: 0
  pull_domain: 0
- name: Authentication API ExplorerSingle Sign On & Token Based
  url: 'https://auth0.com/docs/api/authentication'
  pull_url: 0
  pull_domain: 0
- name: Product Feature Tour  Runscope API Monitoring
  url: 'https://www.runscope.com/product'
  pull_url: 0
  pull_domain: 0
- name: Optus SMS Suite Campaign Manager APIOptus - Confluence
  url: >-
    https://confluence.modicagroup.com/display/OPTUS/Optus+SMS+Suite+Campaign+Manager+API
  pull_url: 0
  pull_domain: 0
- name: 46elksAPI reference
  url: 'https://46elks.se/docs/api-hooks-specification'
  pull_url: 0
  pull_domain: 0
- name: 3GPP specification CRs 29.122
  url: 'https://www.3gpp.org/DynaReport/29122-CRs.htm'
  pull_url: 0
  pull_domain: 0
- name: '[YAML] openapi 3.0.1 info: title: Sms-Uslugi.ru API'
  url: 'https://pastebin.com/eLEZgRx5'
  pull_url: 0
  pull_domain: 0
- name: 'Tyk Open Source API Gateway, API Management Platform'
  url: 'https://tyk.io/'
  pull_url: 0
  pull_domain: 0
- name: Swashbuckle Pro Tips for ASP.NET Web APIKloud Blog
  url: >-
    https://blog.kloud.com.au/2017/08/22/swashbuckle-pro-tips-for-aspnet-web-api-part-3/
  pull_url: 0
  pull_domain: 0
- name: Zapier The easiest way to automate your work
  url: 'https://zapier.com/'
  pull_url: 0
  pull_domain: 0
- name: AWS Documentation
  url: 'https://docs.aws.amazon.com/index.html'
  pull_url: 0
  pull_domain: 0
- name: Sberbank  openAPI portl
  url: 'https://www.apiportal.cz/sberbank/'
  pull_url: 0
  pull_domain: 0
- name: AWS aws_api_gateway_rest_apiTerraform by HashiCorp
  url: 'https://www.terraform.io/docs/providers/aws/r/api_gateway_rest_api.html'
  pull_url: 0
  pull_domain: 0
- name: Tuya Smart Cloud Platform Overview
  url: 'https://docs.tuya.com/en/openapi/'
  pull_url: 0
  pull_domain: 0
- name: Solved SMS Notifications using TwilioCisco Community
  url: >-
    https://community.cisco.com/t5/identity-services-engine-ise/sms-notifications-using-twilio/td-p/3470087
  pull_url: 0
  pull_domain: 0
- name: Azure API Apps  API service Microsoft Azure
  url: 'https://azure.microsoft.com/en-us/services/app-service/api/'
  pull_url: 0
  pull_domain: 0
- name: WSCLI command line tool and SDK for PHP
  url: 'https://isecurefi.github.io/wscli-php/'
  pull_url: 0
  pull_domain: 0
- name: All APIs list Pearson Developers Network
  url: 'http://developer.pearson.com/apis/'
  pull_url: 0
  pull_domain: 0
- name: openapi-toolboxThis is my openapi toolbox.
  url: 'https://www.findbestopensource.com/product/kinlane-openapi-toolbox'
  pull_url: 0
  pull_domain: 0
- name: Creating Help Pages for ASP.NET Web APIASP.NET 4.x
  url: >-
    https://docs.microsoft.com/en-us/aspnet/web-api/overview/getting-started-with-aspnet-web-api/creating-api-help-pages
  pull_url: 0
  pull_domain: 0
- name: 'Relationship Between OpenAPI Path, Summary, Tags and'
  url: >-
    https://apievangelist.com/2018/02/20/relationship-between-openapi-path-summary-tags-and-asyncapi-topics/
  pull_url: 0
  pull_domain: 0
- name: API security Ways to authenticate and authorize
  url: >-
    https://blogs.mulesoft.com/dev/api-dev/api-security-ways-to-authenticate-and-authorize/
  pull_url: 0
  pull_domain: 0
- name: Weather APIOpenWeatherMap
  url: 'https://openweathermap.org/api'
  pull_url: 0
  pull_domain: 0
- name: Swagger (@SwaggerApi) Twitter
  url: 'https://twitter.com/swaggerapi'
  pull_url: 0
  pull_domain: 0
- name: WhatsApp API  How to use the WhatsApp Chat API
  url: 'https://blog.cloudrail.com/whatsapp-api-how-to-use-the-whatsapp-chat-api/'
  pull_url: 0
  pull_domain: 0
- name: API Overview HubSpot API
  url: 'https://developers.hubspot.com/docs/overview'
  pull_url: 0
  pull_domain: 0
- name: WebAPI Discovery Community GroupWorld Wide Web
  url: 'https://www.w3.org/community/web-api-discovery/'
  pull_url: 0
  pull_domain: 0
- name: D&B Direct API
  url: 'https://developer.dnb.com/'
  pull_url: 0
  pull_domain: 0
- name: 'Tutorial Mojolicious::Plugin::OpenAPI: ParametersDEV'
  url: 'https://dev.to/jonasbn/tutorial-mojoliciouspluginopenapi-parameters-4ejj'
  pull_url: 0
  pull_domain: 0
- name: 'APIs, API Business Hub and API Management Whats new in'
  url: >-
    https://blogs.sap.com/2017/09/24/apis-api-business-hub-and-api-management-whats-new-in-teched-17/
  pull_url: 0
  pull_domain: 0
- name: Gizwits Open APIGizwits
  url: 'http://docs.gizwits.com/en-us/cloud/OpenAPI.html'
  pull_url: 0
  pull_domain: 0
- name: approve-api-swagger  PyPI
  url: 'https://pypi.org/project/approve-api-swagger/'
  pull_url: 0
  pull_domain: 0
- name: Connectivity and APIs Saxo Group
  url: >-
    https://www.home.saxo/institutional-and-partners/solutions/connectivity-and-apis
  pull_url: 0
  pull_domain: 0
- name: API MarketplaceFree Public & Open Rest APIs Rakuten
  url: 'https://english.api.rakuten.net/'
  pull_url: 0
  pull_domain: 0
- name: REST API Error Handling Best Practicesblog.restcase.com
  url: 'https://blog.restcase.com/rest-api-error-codes-101/'
  pull_url: 0
  pull_domain: 0
- name: openapi Telruptive
  url: 'https://telruptive.wordpress.com/tag/openapi/'
  pull_url: 0
  pull_domain: 0
- name: How can I use the PRTG Application Programming Interface
  url: >-
    https://kb.paessler.com/en/topic/593-how-can-i-use-the-prtg-application-programming-interface-api
  pull_url: 0
  pull_domain: 0
- name: open api seminarSlideShare
  url: 'https://www.slideshare.net/FGMyk/open-api-seminar'
  pull_url: 0
  pull_domain: 0
- name: AliPay sandbox environment (API for testing)Stack Overflow
  url: >-
    https://stackoverflow.com/questions/37452271/alipay-sandbox-environment-api-for-testing
  pull_url: 0
  pull_domain: 0
- name: Public APIs vs Private APIs What's the Difference?Upwork
  url: >-
    https://www.upwork.com/hiring/development/public-apis-vs-private-apis-whats-the-difference/
  pull_url: 0
  pull_domain: 0
- name: Node JS Frameworks for REST APIsThe Zapier Engineering
  url: 'https://zapier.com/engineering/javascript-api-frameworks/'
  pull_url: 0
  pull_domain: 0
- name: Documentation for Kongv1.2.x Kong - Open-Source API
  url: 'https://docs.konghq.com/'
  pull_url: 0
  pull_domain: 0
